name: notfromaroundhere
favicon: null
layout_spectrum: 0.11555997631512582
typography_spectrum: 0.6871101278811693
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.470304440241307
  lightness: 0.821543380850926
  saturation: 0.007340851705521345
  rhythmicContrast: 0.3433488050941378
purpose: []
